#        Т С   Ч
# РЛНМ П     Ш
#        К Х  Ф

Р: hsl(160, 80%, 40%)
Л: hsl(150, 80%, 40%)
Н: hsl(140, 80%, 40%)
М: hsl(120, 80%, 40%)
П: hsl(80, 100%, 60%)
Т: hsl(50, 100%, 60%)
К: hsl(40, 80%,  55%)
С: hsl(30, 100%, 70%)
Ш: hsl(0,   70%, 80%)
Ч: hsl(-40, 80%, 80%)

Х: hsl(20, 80%,  55%)
Ф: hsl(13, 80%,  55%)

Б: hsl(80, 100%, 30%) #п*
В: hsl(13, 70%,  40%) #ф*
Г: hsl(40, 80%,  30%) #к*
Д: hsl(50, 100%, 35%) #т*
Ж: hsl(0,   70%, 60%) #ш*
З: hsl(50, 100%, 40%) #с*
Ц: hsl(40, 100%, 70%) #тс
Щ: hsl(0,   90%, 80%) #'ш`'
Й: hsl(-80, 60%, 60%) #j